on: 
  push:
    branches:
    - main
jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: '43.254.43.35'
        port: 12586
        username: 'lollypop'
        password: 'T3rr@l0g!c'
        localPath: './'
        remotePath: '/var/www/html/navikenzcms'
